### ISSUE TITLE
Conda direct download?

### ISSUE THREAD

**Issue by AntonioBaeza** [PalMuc/TransPi#3]
Great pipeline! Looking forward to use it. Any chance we can download the program directly from Conda? Thanks!

**Comment by rivera10** [comment]
Hello,
We are working on that for a future update. In the meantime you can clone the repository and do the installation with the `precheck_TransPi.sh`. Essentially the precheck is using conda to install the dependencies. Let me now if you have further questions. 
Thanks

**Comment by rivera10** [comment]
Hello,

We worked on several ways on how to deploy the tool as a conda package but not of them are efficient. Mainly because how the pipeline is structured and the conflicting versions in some of the software. Now each process will have a separate conda installation, following the best practices of the Nextflow community. 

Best,
Ramon
